[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# eth_rpc_url = '${SEPOLIA_RPC_URL}'

etherscan_api = '${ETHERSCAN_API}'

remappings = [
    "openzeppelin-contracts-08/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
