[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# eth_rpc_url = '${ALCHEMY_SEPOLIA_FORK_URL}'
sepolia = "${ALCHEMY_SEPOLIA_FORK_URL}"

# etherscan_api = '${ETHERSCAN_API}'


remappings = [
    "openzeppelin-contracts-08/=lib/openzeppelin-contracts/contracts/",
    "ethernaut/=lib/ethernaut/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
